#!/bin/sh

EXTRA_DEB_PACKAGES=(
	libmp3lame0.deb
	libtwolame0.deb
	libmpeg2-4.deb
	liba52.deb
	libdca0.deb
	libxvidcore4.deb
	libpostproc52.deb
	libavutil54.deb
	libavresample2.deb
	libavcodec56.deb
	libavcodec-extra-56.deb
	libavformat56.deb
	libswscale3.deb
	libx264-142.deb
	libasound-plugins.deb
	libdvdcss2.deb
	libvo-aacenc0.deb
	libvo-amrwbenc0.deb
	libopencore-amrnb0.deb
	libopencore-amrwb0.deb
	libshine3.deb
	libfaad2.deb
	librtmp1.deb
	libgnutls-deb0.deb
	libsidplay2.deb
	libresid-builder0c2a.deb
	libmpcdec6.deb
	libvcdinfo0.deb
	liblivemedia23.deb
	libgroupsock1.deb
	libbasicusageenvironment0.deb
	libusageenvironment1.deb
	vlc-data.deb
	libvlccore8.deb
	libvlc5.deb
	vlc-nox.deb
	vlc.deb
)

for pkg in "${EXTRA_DEB_PACKAGES[@]}"; do
	ar x $pkg
	rm -f $pkg
	tar xf data.tar.*
	rm -f control.tar.gz data.tar.* debian-binary
	cp -R usr/* .
	rm -rf usr
done
